In [ ]:
def Rob_init(self, name):
    self.name = name

Robot2 = type("Robot2", 
              (), 
              {"counter":0, 
               "__init__": Rob_init,
               "sayHello": lambda self: "Hi, I am " + self.name})

In [ ]:
x = Robot2("Marvin")
print(x.name)
print(x.sayHello())

Marvin
Hi, I am Marvin


In [ ]:
from ast import arg
from unicodedata import name


def func1(x):
    return 5+x

def solve_for(self, name:str, args):
    do = f"cv2"
    if hasattr(self, do):
            print('true1')
            if callable(func := getattr(self, do)):
                print('true2')
                res=getattr(self, do)(args)
                print(res)

                # func(args)

def init_func(self, color):
        self._color = color
        setattr(self,'cv'+str(2), func1)

def drive(self):
    print("You are driving the car")

Car = type(
    'Car',
    (object,),
    {
        '__init__': init_func,
        'drive': drive,
        'solve_for':solve_for
    })

my_car = Car('red')
my_car.drive()
my_car.__init__('red')
# exec(f"my_car.cv2()")
# my_car.cv2(6)
my_car.solve_for(name='name:str',args= 52)


You are driving the car
true1
true2
57


In [ ]:
f"cv2" + str(2)

'cv22'

In [ ]:
# Define functions f_0 to f_9
for i in range(10):
    exec(f"def f_{i}(): print({i})")
# Run functions f_0 to f_9
for i in range(10):
    exec(f"f_{i}()")

0
1
2
3
4
5
6
7
8
9


In [ ]:
def solve_for(self, name: str):
    do = f"get_{name}"
    if hasattr(self, do) and callable(getattr(self, do)):
        func = getattr(self, do)
        func()
        
        
def solve_for(self, name: str, *args, **kwargs):
    do = f"get_{name}"
    if hasattr(self, do) and callable(func := getattr(self, do)):
        func(*args, **kwargs)

In [ ]:
'y' + str(2)

'y2'

In [ ]:
l = list(range(1, 5))
print(l)    # [1, 2, 3, 4]
l.pop()

[1, 2, 3, 4]


4

In [ ]:
exec("""def a(x):
...   return x+1""")
a(2)

3

In [ ]:
class Foo:
    def __init__(self, v):
        self.v = v
        
def my_new_method(self):
    print("self.v =", self.v)
    
def my_new_method2(self,x):
    print("self.v2 =", self.v+x)

setattr(Foo, 'print_v', my_new_method)
setattr(Foo, 'print_v2', my_new_method2)


Foo(5).print_v()
Foo(5).print_v2(4)

self.v = 5
self.v2 = 9


In [ ]:
for index in range(7):
    print(index)

0
1
2
3
4
5
6


In [ ]:
for index in range(1,7):
    print(index)


1
2
3
4
5
6


In [ ]:
target = torch.randn(3, 5).softmax(dim=1)
print(target)
target = target.softmax(dim=1)
print(target)

tensor([[0.2797, 0.0627, 0.1354, 0.0223, 0.4998],
        [0.0665, 0.1286, 0.0821, 0.6873, 0.0354],
        [0.1463, 0.0831, 0.3935, 0.2619, 0.1153]])
tensor([[0.2132, 0.1716, 0.1846, 0.1648, 0.2657],
        [0.1692, 0.1800, 0.1719, 0.3148, 0.1640],
        [0.1883, 0.1768, 0.2411, 0.2113, 0.1825]])


In [ ]:
m = nn.Conv1d(16, 33, kernel_size= 5, stride=2)
input = torch.randn(20, 16, 50)
output = m(input)

In [ ]:
from torchinfo import summary

m = nn.Conv1d(1, 100, kernel_size= 3, stride=60)
input = torch.randn(32, 1, 78)
output = m(input)
output.shape


torch.Size([32, 100, 2])

In [ ]:
s=summary(m, input_size=(32, 1, 78))

type(s)
s.total_params
s.trainable_params
s.total_params

400

In [ ]:
s=summary(m, input_size=(32, 1, 78), device='cuda')
l=s.summary_list[0]
l.output_size


[32, 100, 2]

In [ ]:
import torchvision

model = torchvision.models.resnet152()
s=summary(model, (1, 3, 224, 300), depth=3)
l=s.summary_list[4]
l.output_size

[1, 64, 56, 75]

In [ ]:
import torch
import torch.nn as nn

In [ ]:
m = nn.Conv1d(78, 100, kernel_size= 1, stride=5)
input = torch.randn(32, 78, 1)
output = m(input)
output.shape

torch.Size([32, 100, 1])

In [ ]:
# pool with window of size=3, stride=2
m = nn.AvgPool1d(3, stride=2)
target = torch.randn(2, 3)
print(target)
m(target)

tensor([[-0.2892,  0.9355,  0.2475],
        [-1.2642,  0.0045, -0.6432]])


tensor([[ 0.2979],
        [-0.6343]])

In [ ]:
# With Learnable Parameters
m = nn.BatchNorm1d(100)
# Without Learnable Parameters
m = nn.BatchNorm1d(100, affine=False)
input = torch.randn(2, 100)
output = m(input)
print(output.shape)

torch.Size([2, 100])


In [ ]:
rnn = nn.GRU(input_size=10, hidden_size = 20, num_layers =2)
input = torch.randn(5, 3, 10)
h0 = torch.randn(2, 3, 20)
output, hn = rnn(input, h0)
output.shape

torch.Size([5, 3, 20])

In [ ]:
       
input = torch.randn(32, 1, 284)       
outputs = input.permute(0, 2, 1)
outputs.shape

torch.Size([32, 284, 1])

In [ ]:
input = torch.randn(32, 1, 284)       
input=input.squeeze()
input.shape

torch.Size([32, 284])

In [ ]:
input = torch.randn(32, 3, 284)       

input=input.view(-1,284)
input.shape

torch.Size([96, 284])

In [5]:
import torch

input1 = torch.randn(32, 1, 284)    
input2 = torch.randn(32, 284, 1)
print(input1.squeeze(1).shape)
print(input2.squeeze(2).shape)


input3 = torch.randn(32)
print(input3.unsqueeze(1).shape)


torch.Size([32, 284])
torch.Size([32, 284])
torch.Size([1, 32])


In [14]:
criterion = torch.nn.CrossEntropyLoss()
input = torch.randn(32, 64, 1)  
target = torch.randn(32,1) 
   
loss = criterion(input, target.long())


IndexError: Target -2 is out of bounds.

In [ ]:
criterion = torch.nn.CrossEntropyLoss()
input = torch.randn(32, 7)  
target = torch.randn(32) 
   
loss = criterion(input, target.long())


IndexError: Target -1 is out of bounds.

In [7]:
try:
 a = int(input("Enter a positive integer: "))
 if a <= 0:
    raise ValueError("That is not a positive number!")
except ValueError as ve:
    print(ve)